### ISSUE TITLE
Accessibility for Information in Images

### ISSUE THREAD

**Issue by MicheleTobias** [ucdavisdatalab/workshop_introduction_to_version_control#3]
**Issue:** 
Some important information is contained in image with no text to describe them.  For example Section 2.1, images `mac_finder_1.png` and `mac_window_2.png` show file-name-based version control systems, but there is no text to help readers understand what they should learn from the images. It may not be obvious to a new learner and definitely not clear to someone using a screen reader. 

**Solutions:** 

- It would be more clear to include some text to describe what people should learn from these images (or just write out the lesson to be learned and refer to the image) so we make sure we spell it out and they aren't left guessing.
- Add alt text to the images so screen readers can describe the images.

**Comment by t-shoemaker** [comment]
I've added alt text for all images in this reader. Thanks for the catch!
